name: Hello World

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: echo "Hello from GitHub Actions!"
    
    - name: Show Environment
      run: |
        echo "OS: $(uname -s)"
        echo "Architecture: $(uname -m)"
        echo "Python: $(python3 --version)"
        echo "GitHub Repository: ${{ github.repository }}" 